version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ffase2-microfrontend
      POSTGRES_DB: fiap-fase2-microfront
    ports:
      - "5432:5432" # Mapeia a porta do banco de dados para o seu host
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persiste os dados entre reinicializações
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
